# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: books.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 2, "", "books.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0b\x62ooks.proto\x12\x05\x62ooks"\x1d\n\rBookIdRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t"S\n\x0c\x42ookResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x16\n\x0epublished_date\x18\x04 \x01(\t"7\n\x11\x42ooksListResponse\x12"\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x13.books.BookResponse"\x07\n\x05\x45mpty2~\n\x0b\x42ookService\x12\x38\n\x0bGetBookById\x12\x14.books.BookIdRequest\x1a\x13.books.BookResponse\x12\x35\n\x0bGetAllBooks\x12\x0c.books.Empty\x1a\x18.books.BooksListResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "books_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_BOOKIDREQUEST"]._serialized_start = 22
    _globals["_BOOKIDREQUEST"]._serialized_end = 51
    _globals["_BOOKRESPONSE"]._serialized_start = 53
    _globals["_BOOKRESPONSE"]._serialized_end = 136
    _globals["_BOOKSLISTRESPONSE"]._serialized_start = 138
    _globals["_BOOKSLISTRESPONSE"]._serialized_end = 193
    _globals["_EMPTY"]._serialized_start = 195
    _globals["_EMPTY"]._serialized_end = 202
    _globals["_BOOKSERVICE"]._serialized_start = 204
    _globals["_BOOKSERVICE"]._serialized_end = 330
# @@protoc_insertion_point(module_scope)
